"""
Predictive Research Planning (Phase 4).

Analyzes user research history and current context to:
  - Predict what research questions the user might explore next
  - Suggest structured research plans with milestones
  - Identify knowledge gaps in existing research
  - Generate research roadmaps with dependencies
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Optional

from backend.core.logger import get_logger

logger = get_logger(__name__)


@dataclass
class ResearchTopic:
    """A topic extracted from user research history."""
    topic: str
    frequency: int = 1
    last_accessed: float = field(default_factory=time.time)
    confidence: float = 0.5
    related_topics: list[str] = field(default_factory=list)
    source_sessions: list[str] = field(default_factory=list)


@dataclass
class KnowledgeGap:
    """Identified gap in the user's research knowledge."""
    topic: str
    reason: str
    priority: str = "medium"  # high, medium, low
    suggested_queries: list[str] = field(default_factory=list)
    related_existing_topics: list[str] = field(default_factory=list)


@dataclass
class ResearchMilestone:
    """A single milestone in a research plan."""
    title: str
    description: str
    estimated_time: str = ""
    dependencies: list[str] = field(default_factory=list)
    queries: list[str] = field(default_factory=list)
    order: int = 0
    status: str = "pending"  # pending, in_progress, complete


@dataclass
class ResearchPlan:
    """A structured research plan generated by the predictive engine."""
    title: str
    description: str
    milestones: list[ResearchMilestone] = field(default_factory=list)
    estimated_total_time: str = ""
    difficulty: str = "intermediate"  # beginner, intermediate, advanced
    prerequisites: list[str] = field(default_factory=list)
    generated_at: float = field(default_factory=time.time)
    topic: str = ""


@dataclass
class PredictionResult:
    """Result from the predictive planning engine."""
    predicted_topics: list[ResearchTopic] = field(default_factory=list)
    knowledge_gaps: list[KnowledgeGap] = field(default_factory=list)
    suggested_plans: list[ResearchPlan] = field(default_factory=list)
    research_score: float = 0.0  # 0-1, how active/focused the research is
    insights: list[str] = field(default_factory=list)


class PredictiveResearchPlanner:
    """
    AI-powered predictive research planning engine.

    Analyzes research history to predict next topics, identify gaps,
    and generate structured research plans.

    Usage:
        planner = PredictiveResearchPlanner()
        result = await planner.predict_next_topics(user_id, session_history)
        plan = await planner.generate_research_plan("quantum computing basics")
    """

    # --- Topic adjacency map for prediction ---
    # Maps common topics to their natural next-steps
    _TOPIC_TRANSITIONS: dict[str, list[tuple[str, float]]] = {
        "machine learning": [
            ("deep learning architectures", 0.8), ("neural network optimization", 0.7),
            ("model deployment strategies", 0.6), ("MLOps best practices", 0.5),
        ],
        "artificial intelligence": [
            ("AI safety and alignment", 0.8), ("large language models", 0.75),
            ("AI ethics and governance", 0.6), ("AI in enterprise", 0.5),
        ],
        "large language models": [
            ("RAG architectures", 0.8), ("fine-tuning strategies", 0.7),
            ("prompt engineering", 0.65), ("LLM evaluation benchmarks", 0.5),
            ("multi-agent systems", 0.6),
        ],
        "quantum computing": [
            ("quantum algorithms", 0.8), ("quantum error correction", 0.7),
            ("quantum cryptography", 0.65), ("quantum hardware comparison", 0.5),
        ],
        "cybersecurity": [
            ("zero trust architecture", 0.7), ("threat modeling", 0.65),
            ("incident response", 0.6), ("SOC2 compliance", 0.5),
        ],
        "cloud computing": [
            ("kubernetes orchestration", 0.75), ("serverless architecture", 0.65),
            ("cloud cost optimization", 0.6), ("multi-cloud strategies", 0.5),
        ],
        "data science": [
            ("statistical modeling", 0.7), ("data visualization", 0.6),
            ("feature engineering", 0.65), ("experiment design", 0.5),
        ],
        "blockchain": [
            ("smart contract security", 0.7), ("defi protocols", 0.65),
            ("layer 2 scaling", 0.6), ("enterprise blockchain adoption", 0.5),
        ],
    }

    # Common knowledge gap patterns
    _GAP_PATTERNS: list[dict] = [
        {
            "trigger_topics": ["machine learning", "deep learning"],
            "gap_topic": "statistical foundations",
            "reason": "Strong understanding of statistics is fundamental to ML/DL.",
            "queries": ["statistical methods for machine learning", "probability theory for deep learning"],
        },
        {
            "trigger_topics": ["large language models", "RAG"],
            "gap_topic": "evaluation and benchmarking",
            "reason": "LLM outputs need rigorous evaluation frameworks.",
            "queries": ["LLM evaluation metrics and benchmarks", "RAG system evaluation methods"],
        },
        {
            "trigger_topics": ["cloud computing", "kubernetes"],
            "gap_topic": "security and compliance",
            "reason": "Cloud deployments require robust security posture.",
            "queries": ["kubernetes security best practices", "cloud compliance frameworks"],
        },
        {
            "trigger_topics": ["artificial intelligence", "AI safety"],
            "gap_topic": "AI governance and regulation",
            "reason": "AI deployment requires understanding of emerging regulations.",
            "queries": ["AI governance frameworks 2024", "EU AI Act implications"],
        },
    ]

    # --- Research plan templates ---
    _PLAN_TEMPLATES: dict[str, dict] = {
        "default": {
            "milestones": [
                {"title": "Landscape Survey", "description": "Map the research landscape and key players",
                 "time": "2-3 hours", "queries": ["{topic} overview 2024", "{topic} key research papers"]},
                {"title": "Core Concepts", "description": "Understand fundamental concepts and terminology",
                 "time": "3-4 hours", "queries": ["{topic} fundamentals", "{topic} glossary concepts"]},
                {"title": "Technical Deep Dive", "description": "Explore technical details and implementations",
                 "time": "4-6 hours", "queries": ["{topic} architecture details", "{topic} implementation guide"]},
                {"title": "Case Studies", "description": "Study real-world applications and outcomes",
                 "time": "2-3 hours", "queries": ["{topic} case studies", "{topic} enterprise adoption"]},
                {"title": "Comparison & Analysis", "description": "Compare approaches and analyze trade-offs",
                 "time": "2-3 hours", "queries": ["{topic} comparison 2024", "{topic} pros and cons analysis"]},
                {"title": "Synthesis & Report", "description": "Synthesize findings into actionable insights",
                 "time": "2-3 hours", "queries": ["{topic} best practices", "{topic} future trends"]},
            ],
            "total_time": "15-22 hours",
            "difficulty": "intermediate",
        },
        "quick": {
            "milestones": [
                {"title": "Quick Overview", "description": "High-level summary of the topic",
                 "time": "1 hour", "queries": ["{topic} overview", "{topic} key points"]},
                {"title": "Key Findings", "description": "Identify the most important findings",
                 "time": "1-2 hours", "queries": ["{topic} important findings 2024", "{topic} latest developments"]},
                {"title": "Summary Report", "description": "Create a concise summary",
                 "time": "1 hour", "queries": ["{topic} executive summary"]},
            ],
            "total_time": "3-4 hours",
            "difficulty": "beginner",
        },
    }

    def __init__(self):
        self._topic_cache: dict[str, list[ResearchTopic]] = {}  # user_id -> topics

    # ------------------------------------------------------------------
    # Predict Next Topics
    # ------------------------------------------------------------------
    async def predict_next_topics(
        self,
        user_id: str,
        session_history: list[dict[str, Any]],
    ) -> PredictionResult:
        """Analyze session history and predict what the user might research next.

        Args:
            user_id: The user's ID.
            session_history: List of session dicts with 'query', 'topics', 'tags', 'created_at'.

        Returns:
            PredictionResult with predicted topics, gaps, and insights.
        """
        # Extract topics from history
        topics = self._extract_topics_from_history(session_history)
        self._topic_cache[user_id] = topics

        # Predict next topics using transition patterns
        predicted = self._predict_from_transitions(topics)

        # Identify knowledge gaps
        gaps = self._identify_gaps(topics)

        # Generate research score
        research_score = self._calculate_research_score(session_history)

        # Generate insights
        insights = self._generate_insights(topics, session_history)

        return PredictionResult(
            predicted_topics=predicted[:10],
            knowledge_gaps=gaps,
            research_score=research_score,
            insights=insights,
        )

    # ------------------------------------------------------------------
    # Generate Research Plan
    # ------------------------------------------------------------------
    async def generate_research_plan(
        self,
        topic: str,
        depth: str = "default",
        user_context: Optional[dict[str, Any]] = None,
    ) -> ResearchPlan:
        """Generate a structured research plan for a given topic.

        Args:
            topic: The research topic.
            depth: Plan depth — "quick" (3 milestones) or "default" (6 milestones).
            user_context: Optional context about user's existing knowledge.

        Returns:
            ResearchPlan with milestones and dependencies.
        """
        template = self._PLAN_TEMPLATES.get(depth, self._PLAN_TEMPLATES["default"])
        milestones = []

        for i, m in enumerate(template["milestones"]):
            queries = [q.format(topic=topic) for q in m.get("queries", [])]
            deps = [milestones[i - 1].title] if i > 0 else []

            milestones.append(ResearchMilestone(
                title=m["title"],
                description=m["description"],
                estimated_time=m.get("time", "1-2 hours"),
                dependencies=deps,
                queries=queries,
                order=i + 1,
            ))

        # Add prerequisites based on user context
        prerequisites = []
        if user_context and user_context.get("known_topics"):
            known = set(user_context["known_topics"])
            topic_words = set(topic.lower().split())
            if not topic_words & known:
                prerequisites.append(f"Basic understanding of {topic} concepts")

        plan = ResearchPlan(
            title=f"Research Plan: {topic}",
            description=f"A structured {depth} research plan for '{topic}' with "
                       f"{len(milestones)} milestones and estimated {template['total_time']} of research.",
            milestones=milestones,
            estimated_total_time=template["total_time"],
            difficulty=template["difficulty"],
            prerequisites=prerequisites,
            topic=topic,
        )

        logger.info("research_plan_generated", topic=topic, milestones=len(milestones), depth=depth)
        return plan

    # ------------------------------------------------------------------
    # Suggest Research Plans
    # ------------------------------------------------------------------
    async def suggest_research_plans(
        self,
        user_id: str,
        session_history: list[dict[str, Any]],
    ) -> list[ResearchPlan]:
        """Suggest research plans based on predicted topics.

        Returns top 3 suggested plans with milestones.
        """
        prediction = await self.predict_next_topics(user_id, session_history)
        plans = []

        for topic in prediction.predicted_topics[:3]:
            plan = await self.generate_research_plan(topic.topic, depth="default")
            plan.description = f"Suggested based on your interest in {topic.topic} " \
                             f"(confidence: {topic.confidence:.0%})"
            plans.append(plan)

        return plans

    # ------------------------------------------------------------------
    # Internal Methods
    # ------------------------------------------------------------------
    def _extract_topics_from_history(self, sessions: list[dict]) -> list[ResearchTopic]:
        """Extract and aggregate research topics from session history."""
        topic_map: dict[str, ResearchTopic] = {}

        for session in sessions:
            # Extract from query text
            query = session.get("query", "")
            tags = session.get("tags", [])
            topics_raw = session.get("topics", [])
            session_id = session.get("id", "")

            # Use tags as topic signals
            all_topics = topics_raw + [t.lower().strip() for t in tags if isinstance(t, str)]

            # Also extract from query (simple keyword extraction)
            if query:
                words = query.lower().split()
                # Skip common words
                skip = {"what", "how", "why", "is", "are", "the", "a", "an", "for", "to", "of", "in", "and", "or", "on", "with", "about", "latest", "best", "new"}
                meaningful = [w for w in words if w not in skip and len(w) > 3]
                # Take bigrams as topics
                for i in range(len(meaningful) - 1):
                    bigram = f"{meaningful[i]} {meaningful[i+1]}"
                    all_topics.append(bigram)

            for topic in all_topics:
                topic = topic.lower().strip()
                if not topic or len(topic) < 3:
                    continue

                if topic in topic_map:
                    topic_map[topic].frequency += 1
                    topic_map[topic].last_accessed = max(
                        topic_map[topic].last_accessed,
                        session.get("created_at", time.time())
                    )
                    if session_id and session_id not in topic_map[topic].source_sessions:
                        topic_map[topic].source_sessions.append(session_id)
                else:
                    topic_map[topic] = ResearchTopic(
                        topic=topic,
                        frequency=1,
                        last_accessed=session.get("created_at", time.time()),
                        source_sessions=[session_id] if session_id else [],
                    )

        # Sort by frequency and recency
        topics = sorted(topic_map.values(), key=lambda t: t.frequency * 2 + (t.last_accessed / 1e10), reverse=True)
        return topics[:30]

    def _predict_from_transitions(self, topics: list[ResearchTopic]) -> list[ResearchTopic]:
        """Predict next topics using the transition adjacency map."""
        predicted: list[ResearchTopic] = []
        existing_topics = {t.topic for t in topics}

        for topic in topics[:10]:
            # Look for matching transition patterns
            for key, transitions in self._TOPIC_TRANSITIONS.items():
                if key in topic.topic or topic.topic in key:
                    for next_topic, confidence in transitions:
                        if next_topic not in existing_topics:
                            predicted.append(ResearchTopic(
                                topic=next_topic,
                                confidence=confidence * (topic.frequency / max(topics[0].frequency, 1)),
                                related_topics=[topic.topic],
                            ))
                            existing_topics.add(next_topic)

        # Also predict based on topic co-occurrence
        if len(topics) >= 2:
            top_topics = [t.topic for t in topics[:5]]
            predicted.append(ResearchTopic(
                topic=f"{' and '.join(top_topics[:2])} intersection",
                confidence=0.4,
                related_topics=top_topics[:2],
            ))

        predicted.sort(key=lambda t: t.confidence, reverse=True)
        return predicted

    def _identify_gaps(self, topics: list[ResearchTopic]) -> list[KnowledgeGap]:
        """Identify knowledge gaps based on research patterns."""
        gaps: list[KnowledgeGap] = []
        topic_set = {t.topic for t in topics}

        for pattern in self._GAP_PATTERNS:
            # Check if any trigger topics are in the user's history
            triggered = any(t in topic_set for t in pattern["trigger_topics"])
            # Check if the gap topic is already covered
            gap_covered = pattern["gap_topic"] in topic_set

            if triggered and not gap_covered:
                gaps.append(KnowledgeGap(
                    topic=pattern["gap_topic"],
                    reason=pattern["reason"],
                    priority="high" if len([t for t in pattern["trigger_topics"] if t in topic_set]) >= 2 else "medium",
                    suggested_queries=pattern["queries"],
                    related_existing_topics=[t for t in pattern["trigger_topics"] if t in topic_set],
                ))

        return gaps

    def _calculate_research_score(self, sessions: list[dict]) -> float:
        """Calculate a research activity score (0-1)."""
        if not sessions:
            return 0.0

        # Factors: number of sessions, topic diversity, recency, depth
        num_sessions = min(len(sessions), 50) / 50  # 0-1
        topic_diversity = len(set(
            tag for s in sessions for tag in s.get("tags", [])
        )) / 20  # normalize
        recency = 1.0 if sessions else 0.0

        score = (num_sessions * 0.4 + min(topic_diversity, 1.0) * 0.3 + recency * 0.3)
        return round(min(score, 1.0), 3)

    def _generate_insights(self, topics: list[ResearchTopic], sessions: list[dict]) -> list[str]:
        """Generate actionable research insights."""
        insights = []

        if topics:
            top = topics[0]
            insights.append(f"Your most researched topic is '{top.topic}' with {top.frequency} sessions.")

        if len(topics) >= 3:
            insights.append(f"You've explored {len(topics)} distinct research topics.")

        # Check for focus vs breadth
        if topics and topics[0].frequency > 5:
            insights.append(f"You show deep focus on '{topics[0].topic}' — consider exploring adjacent areas.")
        elif len(topics) > 10:
            insights.append("You have broad research interests — a focused deep dive might yield insights.")

        return insights


# Module-level singleton
predictive_planner = PredictiveResearchPlanner()
