"""
Export Tools — converts agent research reports into corporate deliverables.
Currently supports PPTX Generation.
"""

import os
from pptx import Presentation
from pptx.util import Inches, Pt
from langchain_core.tools import tool
from backend.db.workspace import WorkspaceManager
from backend.core.logger import get_logger

logger = get_logger(__name__)
_ws = WorkspaceManager()

def get_export_tools(session_id: str) -> list:
    """Return export tools bound to a specific session workspace."""

    @tool
    def generate_presentation(title: str, markdown_content: str, filename: str = "presentation.pptx") -> str:
        """
        Generate a fully formatted PowerPoint (.pptx) presentation from a markdown report.
        Automatically splits H2 tags into separate slides and extracts bullet points.
        Saves the resulting file into the session's workspace.
        """
        logger.info("generating_presentation", session_id=session_id, title=title)
        
        try:
            prs = Presentation()
            
            # Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title_box = slide.shapes.title
            subtitle_box = slide.placeholders[1]
            title_box.text = title
            subtitle_box.text = "Generated by CortexAI Autonomous Deep Researcher"
            
            # Parse markdown content (Very rudimentary markdown parser)
            lines = markdown_content.split('\n')
            current_slide = None
            current_body = None
            
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                    
                if line.startswith("## "):
                    # New Slide
                    layout = prs.slide_layouts[1] # Title and Content
                    current_slide = prs.slides.add_slide(layout)
                    title_shape = current_slide.shapes.title
                    title_clean = line.replace("## ", "").replace("*", "").strip()
                    title_shape.text = title_clean
                    current_body = current_slide.shapes.placeholders[1].text_frame
                    current_body.text = "" # Clear default
                elif current_body and line.startswith(("- ", "* ")):
                    # Add bullet point
                    p = current_body.add_paragraph()
                    p.text = line[2:].replace("**", "").replace("*", "").strip()
                    p.font.size = Pt(18)
                elif current_body and not line.startswith("#"):
                    # Add normal text
                    p = current_body.add_paragraph()
                    p.text = line.replace("**", "").replace("*", "").strip()
                    p.font.size = Pt(16)
                    
            # Ensure workspace path exists
            workspace_dir = _ws.get_workspace_path(session_id)
            os.makedirs(workspace_dir, exist_ok=True)
            
            # Save file
            file_path = os.path.join(workspace_dir, filename)
            prs.save(file_path)
            
            return f"Successfully generated presentation: {filename} in workspace."

        except Exception as e:
            logger.error("presentation_generation_failed", session_id=session_id, error=str(e))
            return f"Failed to generate presentation: {str(e)}"

    return [generate_presentation]
