"""
Export Tools — converts agent research reports into corporate deliverables.
Supports PPTX, PDF, and DOCX export formats (Feature Gap #4).
"""

import os
import re
from pptx import Presentation
from pptx.util import Inches, Pt
from langchain_core.tools import tool
from backend.db.workspace import WorkspaceManager
from backend.core.logger import get_logger

logger = get_logger(__name__)
_ws = WorkspaceManager()

def get_export_tools(session_id: str) -> list:
    """Return export tools bound to a specific session workspace."""

    @tool
    def generate_presentation(title: str, markdown_content: str, filename: str = "presentation.pptx") -> str:
        """
        Generate a fully formatted PowerPoint (.pptx) presentation from a markdown report.
        Automatically splits H2 tags into separate slides and extracts bullet points.
        Saves the resulting file into the session's workspace.
        """
        logger.info("generating_presentation", session_id=session_id, title=title)
        
        try:
            prs = Presentation()
            
            # Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title_box = slide.shapes.title
            subtitle_box = slide.placeholders[1]
            title_box.text = title
            subtitle_box.text = "Generated by CortexAI Autonomous Deep Researcher"
            
            # Parse markdown content (Very rudimentary markdown parser)
            lines = markdown_content.split('\n')
            current_slide = None
            current_body = None
            
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                    
                if line.startswith("## "):
                    # New Slide
                    layout = prs.slide_layouts[1] # Title and Content
                    current_slide = prs.slides.add_slide(layout)
                    title_shape = current_slide.shapes.title
                    title_clean = line.replace("## ", "").replace("*", "").strip()
                    title_shape.text = title_clean
                    current_body = current_slide.shapes.placeholders[1].text_frame
                    current_body.text = "" # Clear default
                elif current_body and line.startswith(("- ", "* ")):
                    # Add bullet point
                    p = current_body.add_paragraph()
                    p.text = line[2:].replace("**", "").replace("*", "").strip()
                    p.font.size = Pt(18)
                elif current_body and not line.startswith("#"):
                    # Add normal text
                    p = current_body.add_paragraph()
                    p.text = line.replace("**", "").replace("*", "").strip()
                    p.font.size = Pt(16)
                    
            # Ensure workspace path exists
            workspace_dir = _ws.get_workspace_path(session_id)
            os.makedirs(workspace_dir, exist_ok=True)
            
            # Save file
            file_path = os.path.join(workspace_dir, filename)
            prs.save(file_path)
            
            return f"Successfully generated presentation: {filename} in workspace."

        except Exception as e:
            logger.error("presentation_generation_failed", session_id=session_id, error=str(e))
            return f"Failed to generate presentation: {str(e)}"

    @tool
    def export_report_pdf(title: str, markdown_content: str, filename: str = "report.pdf") -> str:
        """
        Generate a PDF document from a markdown research report.
        Uses WeasyPrint for HTML-to-PDF rendering with basic styling.
        Saves the resulting file into the session's workspace.
        """
        logger.info("generating_pdf", session_id=session_id, title=title)
        try:
            from weasyprint import HTML

            # Convert markdown to simple HTML
            html_body = _markdown_to_html(markdown_content, title)
            html_doc = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; line-height: 1.6; color: #333; }}
  h1 {{ color: #1a1a2e; border-bottom: 2px solid #e94560; padding-bottom: 10px; }}
  h2 {{ color: #16213e; margin-top: 30px; }}
  h3 {{ color: #0f3460; }}
  p {{ margin: 10px 0; }}
  ul, ol {{ padding-left: 25px; }}
  li {{ margin: 4px 0; }}
  blockquote {{ border-left: 3px solid #e94560; padding-left: 15px; color: #555; }}
  code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }}
  table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
  th {{ background: #16213e; color: white; }}
  a {{ color: #e94560; }}
  .footer {{ margin-top: 40px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 0.85em; color: #888; }}
</style>
</head><body>
{html_body}
<div class="footer">Generated by CortexAI Autonomous Deep Researcher</div>
</body></html>"""

            workspace_dir = _ws.get_workspace_path(session_id)
            os.makedirs(workspace_dir, exist_ok=True)
            file_path = os.path.join(workspace_dir, filename)

            HTML(string=html_doc).write_pdf(file_path)
            return f"Successfully generated PDF report: {filename}"
        except ImportError:
            logger.warning("weasyprint_not_installed", session_id=session_id)
            return "PDF export unavailable: install weasyprint (pip install weasyprint)"
        except Exception as e:
            logger.error("pdf_generation_failed", session_id=session_id, error=str(e))
            return f"Failed to generate PDF: {str(e)}"

    @tool
    def export_report_docx(title: str, markdown_content: str, filename: str = "report.docx") -> str:
        """
        Generate a Word (.docx) document from a markdown research report.
        Uses python-docx for document generation with headings, paragraphs,
        bullet lists, and basic formatting.
        Saves the resulting file into the session's workspace.
        """
        logger.info("generating_docx", session_id=session_id, title=title)
        try:
            from docx import Document
            from docx.shared import Pt as DocxPt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH

            doc = Document()

            # Title
            heading = doc.add_heading(title, level=0)
            heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

            # Subtitle
            subtitle = doc.add_paragraph("Generated by CortexAI Autonomous Deep Researcher")
            subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
            subtitle.runs[0].font.size = DocxPt(10)
            subtitle.runs[0].font.color.rgb = RGBColor(128, 128, 128)

            doc.add_paragraph("")  # spacer

            # Parse markdown lines
            for line in markdown_content.split("\n"):
                stripped = line.strip()
                if not stripped:
                    continue
                elif stripped.startswith("### "):
                    doc.add_heading(stripped[4:].replace("**", "").strip(), level=3)
                elif stripped.startswith("## "):
                    doc.add_heading(stripped[3:].replace("**", "").strip(), level=2)
                elif stripped.startswith("# "):
                    doc.add_heading(stripped[2:].replace("**", "").strip(), level=1)
                elif stripped.startswith(("- ", "* ")):
                    text = stripped[2:].replace("**", "").replace("*", "").strip()
                    doc.add_paragraph(text, style="List Bullet")
                elif re.match(r"^\d+\.\s", stripped):
                    text = re.sub(r"^\d+\.\s", "", stripped).replace("**", "").strip()
                    doc.add_paragraph(text, style="List Number")
                elif stripped.startswith("> "):
                    p = doc.add_paragraph(stripped[2:].strip())
                    p.paragraph_format.left_indent = DocxPt(20)
                    p.runs[0].font.italic = True
                else:
                    text = stripped.replace("**", "").replace("*", "").strip()
                    if text:
                        doc.add_paragraph(text)

            workspace_dir = _ws.get_workspace_path(session_id)
            os.makedirs(workspace_dir, exist_ok=True)
            file_path = os.path.join(workspace_dir, filename)
            doc.save(file_path)
            return f"Successfully generated DOCX report: {filename}"
        except ImportError:
            logger.warning("python_docx_not_installed", session_id=session_id)
            return "DOCX export unavailable: install python-docx (pip install python-docx)"
        except Exception as e:
            logger.error("docx_generation_failed", session_id=session_id, error=str(e))
            return f"Failed to generate DOCX: {str(e)}"

    return [generate_presentation, export_report_pdf, export_report_docx]


def _markdown_to_html(markdown: str, title: str) -> str:
    """Minimal markdown-to-HTML converter for PDF export."""
    lines = markdown.split("\n")
    html_parts = [f"<h1>{_escape_html(title)}</h1>"]
    in_list = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            continue

        if stripped.startswith("### "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h3>{_escape_html(stripped[4:])}</h3>")
        elif stripped.startswith("## "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h2>{_escape_html(stripped[3:])}</h2>")
        elif stripped.startswith("# "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h1>{_escape_html(stripped[2:])}</h1>")
        elif stripped.startswith(("- ", "* ")):
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{_inline_format(stripped[2:])}</li>")
        elif re.match(r"^\d+\.\s", stripped):
            text = re.sub(r"^\d+\.\s", "", stripped)
            html_parts.append(f"<p>{_inline_format(text)}</p>")
        elif stripped.startswith("> "):
            html_parts.append(f"<blockquote>{_inline_format(stripped[2:])}</blockquote>")
        else:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<p>{_inline_format(stripped)}</p>")

    if in_list:
        html_parts.append("</ul>")

    return "\n".join(html_parts)


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _inline_format(text: str) -> str:
    """Apply inline markdown formatting (bold, italic, links, code)."""
    text = _escape_html(text)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    # Code
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    # Links
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text
