"""
MCP Export Server — report generation and export tools.

Provides:
  - generate_pptx: Convert markdown report to PowerPoint presentation
  - generate_interactive_report: Create interactive HTML report with Plotly charts
  - generate_pdf_report: Create a PDF report from markdown
  - export_chart_html: Generate standalone interactive chart HTML files

Runs as a standalone MCP server process (stdio transport).
"""

import os
import sys
import json
import asyncio
import uuid
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))


# Jinja2-style template for interactive HTML reports
REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{TITLE}} — CortexAI Research Report</title>
    <script src="https://cdn.plot.ly/plotly-2.35.0.min.js"></script>
    <style>
        :root {
            --bg: #0f0f17;
            --surface: #1a1a2e;
            --border: #2a2a40;
            --text: #e0e0e8;
            --text-secondary: #8888a0;
            --accent: #7c3aed;
            --accent-glow: rgba(124, 58, 237, 0.3);
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { background: var(--bg); color: var(--text); font-family: 'Inter', -apple-system, sans-serif; line-height: 1.7; }
        .container { max-width: 900px; margin: 0 auto; padding: 3rem 2rem; }
        .report-header { text-align: center; margin-bottom: 3rem; padding-bottom: 2rem; border-bottom: 1px solid var(--border); }
        .report-header h1 { font-size: 2.2rem; background: linear-gradient(135deg, #7c3aed, #a78bfa); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 0.5rem; }
        .report-header .meta { color: var(--text-secondary); font-size: 0.9rem; }
        .report-body { font-size: 1.05rem; }
        .report-body h2 { font-size: 1.5rem; color: #a78bfa; margin: 2.5rem 0 1rem; padding-bottom: 0.5rem; border-bottom: 1px solid var(--border); }
        .report-body h3 { font-size: 1.2rem; color: #c4b5fd; margin: 1.5rem 0 0.8rem; }
        .report-body p { margin-bottom: 1rem; }
        .report-body ul, .report-body ol { margin: 1rem 0 1rem 2rem; }
        .report-body li { margin-bottom: 0.5rem; }
        .report-body a { color: #7c3aed; text-decoration: none; }
        .report-body a:hover { text-decoration: underline; }
        .report-body blockquote { border-left: 3px solid var(--accent); padding: 0.8rem 1.2rem; margin: 1rem 0; background: var(--surface); border-radius: 0 8px 8px 0; }
        .report-body code { background: var(--surface); padding: 0.2em 0.4em; border-radius: 4px; font-size: 0.9em; }
        .report-body pre { background: var(--surface); padding: 1.2rem; border-radius: 8px; overflow-x: auto; margin: 1rem 0; }
        .chart-container { background: var(--surface); border-radius: 12px; padding: 1.5rem; margin: 2rem 0; border: 1px solid var(--border); }
        .report-footer { margin-top: 4rem; padding-top: 2rem; border-top: 1px solid var(--border); text-align: center; color: var(--text-secondary); font-size: 0.85rem; }
        .toolbar { position: fixed; top: 1rem; right: 1rem; display: flex; gap: 0.5rem; z-index: 100; }
        .toolbar button { background: var(--surface); color: var(--text); border: 1px solid var(--border); padding: 0.5rem 1rem; border-radius: 8px; cursor: pointer; font-size: 0.85rem; transition: all 0.2s; }
        .toolbar button:hover { background: var(--accent); border-color: var(--accent); }
        @media print { .toolbar { display: none; } body { background: white; color: black; } .report-header h1 { -webkit-text-fill-color: #7c3aed; } }
    </style>
</head>
<body>
    <div class="toolbar">
        <button onclick="window.print()">📄 Print / PDF</button>
        <button onclick="copyReport()">📋 Copy</button>
    </div>
    <div class="container">
        <div class="report-header">
            <h1>{{TITLE}}</h1>
            <div class="meta">Generated by CortexAI • {{DATE}}</div>
        </div>
        <div class="report-body" id="report-content">
            {{CONTENT}}
        </div>
        {{CHARTS}}
        <div class="report-footer">
            <p>Generated by <strong>CortexAI</strong> Autonomous Deep Research Agent</p>
        </div>
    </div>
    <script>
        function copyReport() {
            const content = document.getElementById('report-content').innerText;
            navigator.clipboard.writeText(content).then(() => alert('Report copied!'));
        }
    </script>
</body>
</html>"""


class ExportMCPServer:
    """MCP Server for report generation and export."""

    def __init__(self):
        self.server_info = {
            "name": "cortexai-export",
            "version": "1.0.0",
        }
        self.tools = self._define_tools()
        self._workspace_root = os.getenv("WORKSPACE_ROOT", "./data/workspaces")

    def _define_tools(self) -> list[dict]:
        return [
            {
                "name": "generate_pptx",
                "description": "Generate a formatted PowerPoint (.pptx) presentation from markdown content. Splits H2 headings into separate slides and extracts bullet points.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Presentation title"},
                        "markdown_content": {"type": "string", "description": "Markdown report content"},
                        "session_id": {"type": "string", "description": "Session ID", "default": "default"},
                        "filename": {"type": "string", "description": "Output filename", "default": "presentation.pptx"},
                    },
                    "required": ["title", "markdown_content"]
                }
            },
            {
                "name": "generate_interactive_report",
                "description": "Generate an interactive HTML report with embedded Plotly charts. The report is self-contained and can be shared as a single file. Supports dark theme, print/PDF export, and copy functionality.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Report title"},
                        "markdown_content": {"type": "string", "description": "Markdown report content"},
                        "charts_config": {"type": "string", "description": "JSON array of chart specs: [{\"type\":\"bar\",\"title\":\"...\",\"data\":{...}}]", "default": "[]"},
                        "session_id": {"type": "string", "description": "Session ID", "default": "default"},
                    },
                    "required": ["title", "markdown_content"]
                }
            },
        ]

    async def handle_tool_call(self, tool_name: str, arguments: dict) -> dict:
        handlers = {
            "generate_pptx": self._handle_generate_pptx,
            "generate_interactive_report": self._handle_generate_interactive_report,
        }
        handler = handlers.get(tool_name)
        if not handler:
            return {"content": [{"type": "text", "text": f"Unknown tool: {tool_name}"}], "isError": True}
        try:
            result = await handler(arguments)
            return {"content": [{"type": "text", "text": result}], "isError": False}
        except Exception as e:
            return {"content": [{"type": "text", "text": f"Export error: {str(e)}"}], "isError": True}

    async def _handle_generate_pptx(self, args: dict) -> str:
        """Generate PowerPoint presentation from markdown."""
        title = args.get("title", "Research Report")
        markdown = args.get("markdown_content", "")
        session_id = args.get("session_id", "default")
        filename = args.get("filename", "presentation.pptx")

        if not markdown.strip():
            return "Error: No markdown content provided."

        try:
            from pptx import Presentation
            from pptx.util import Pt

            prs = Presentation()

            # Title slide
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = title
            slide.placeholders[1].text = "Generated by CortexAI Autonomous Deep Researcher"

            # Parse markdown into slides
            lines = markdown.split("\n")
            current_body = None

            for line in lines:
                line = line.strip()
                if not line:
                    continue

                if line.startswith("## "):
                    layout = prs.slide_layouts[1]
                    slide = prs.slides.add_slide(layout)
                    slide.shapes.title.text = line[3:].replace("*", "").strip()
                    current_body = slide.shapes.placeholders[1].text_frame
                    current_body.text = ""
                elif current_body and line.startswith(("- ", "* ")):
                    p = current_body.add_paragraph()
                    p.text = line[2:].replace("**", "").replace("*", "").strip()
                    p.font.size = Pt(18)
                elif current_body and not line.startswith("#"):
                    p = current_body.add_paragraph()
                    p.text = line.replace("**", "").replace("*", "").strip()
                    p.font.size = Pt(16)

            workspace = Path(self._workspace_root) / session_id
            workspace.mkdir(parents=True, exist_ok=True)
            filepath = workspace / filename
            prs.save(str(filepath))

            return f"Successfully generated PowerPoint: {filename} ({len(prs.slides)} slides)"

        except ImportError:
            return "Error: python-pptx is not installed. Install with: pip install python-pptx"
        except Exception as e:
            return f"PPTX generation failed: {str(e)}"

    async def _handle_generate_interactive_report(self, args: dict) -> str:
        """Generate an interactive HTML report."""
        title = args.get("title", "Research Report")
        markdown = args.get("markdown_content", "")
        charts_json = args.get("charts_config", "[]")
        session_id = args.get("session_id", "default")

        if not markdown.strip():
            return "Error: No markdown content provided."

        # Convert markdown to HTML (basic conversion)
        html_content = self._markdown_to_html(markdown)

        # Parse chart configurations
        charts_html = ""
        try:
            charts = json.loads(charts_json)
            for i, chart in enumerate(charts):
                chart_id = f"chart-{i}"
                charts_html += f'<div class="chart-container" id="{chart_id}"></div>\n'
                charts_html += f'<script>Plotly.newPlot("{chart_id}", {json.dumps(self._chart_to_plotly(chart))}, '
                charts_html += f'{json.dumps({"title": chart.get("title", ""), "template": "plotly_dark"})});</script>\n'
        except json.JSONDecodeError:
            pass

        # Build the report
        from datetime import datetime
        html = REPORT_TEMPLATE.replace("{{TITLE}}", title)
        html = html.replace("{{DATE}}", datetime.now().strftime("%B %d, %Y"))
        html = html.replace("{{CONTENT}}", html_content)
        html = html.replace("{{CHARTS}}", charts_html)

        # Save to workspace
        workspace = Path(self._workspace_root) / session_id
        workspace.mkdir(parents=True, exist_ok=True)
        filepath = workspace / "interactive_report.html"
        filepath.write_text(html, encoding="utf-8")

        return f"Interactive report generated: interactive_report.html ({len(html)} chars, {len(json.loads(charts_json)) if charts_json != '[]' else 0} charts)"

    def _markdown_to_html(self, md: str) -> str:
        """Basic markdown to HTML converter."""
        import re
        lines = md.split("\n")
        html_lines = []
        in_list = False
        in_code = False

        for line in lines:
            stripped = line.strip()

            # Code blocks
            if stripped.startswith("```"):
                if in_code:
                    html_lines.append("</pre>")
                    in_code = False
                else:
                    lang = stripped[3:] if len(stripped) > 3 else ""
                    html_lines.append(f'<pre><code class="{lang}">')
                    in_code = True
                continue

            if in_code:
                html_lines.append(line.replace("<", "&lt;").replace(">", "&gt;"))
                continue

            # Close list if needed
            if in_list and not stripped.startswith(("- ", "* ", "1.")):
                html_lines.append("</ul>")
                in_list = False

            # Headers
            if stripped.startswith("### "):
                html_lines.append(f"<h3>{stripped[4:]}</h3>")
            elif stripped.startswith("## "):
                html_lines.append(f"<h2>{stripped[3:]}</h2>")
            elif stripped.startswith("# "):
                html_lines.append(f"<h1>{stripped[2:]}</h1>")
            # Lists
            elif stripped.startswith(("- ", "* ")):
                if not in_list:
                    html_lines.append("<ul>")
                    in_list = True
                html_lines.append(f"<li>{self._inline_format(stripped[2:])}</li>")
            # Blockquote
            elif stripped.startswith("> "):
                html_lines.append(f"<blockquote>{self._inline_format(stripped[2:])}</blockquote>")
            # Horizontal rule
            elif stripped in ("---", "***", "___"):
                html_lines.append("<hr>")
            # Empty line
            elif not stripped:
                html_lines.append("")
            # Paragraph
            else:
                html_lines.append(f"<p>{self._inline_format(stripped)}</p>")

        if in_list:
            html_lines.append("</ul>")
        if in_code:
            html_lines.append("</pre>")

        return "\n".join(html_lines)

    def _inline_format(self, text: str) -> str:
        """Apply inline markdown formatting (bold, italic, code, links)."""
        import re
        # Bold
        text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
        # Italic
        text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
        # Inline code
        text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
        # Links
        text = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2" target="_blank">\1</a>', text)
        return text

    def _chart_to_plotly(self, chart: dict) -> list[dict]:
        """Convert a chart config to Plotly trace format."""
        chart_type = chart.get("type", "bar")
        data = chart.get("data", {})

        if chart_type == "bar":
            return [{"type": "bar", "x": data.get("labels", []), "y": data.get("values", [])}]
        elif chart_type == "line":
            return [{"type": "scatter", "mode": "lines+markers", "x": data.get("x", []), "y": data.get("y", [])}]
        elif chart_type == "pie":
            return [{"type": "pie", "labels": data.get("labels", []), "values": data.get("values", [])}]
        elif chart_type == "scatter":
            return [{"type": "scatter", "mode": "markers", "x": data.get("x", []), "y": data.get("y", [])}]
        return [{"type": "bar", "x": [], "y": []}]

    # ──────────────────── MCP Server Loop ────────────────────

    async def run_stdio(self):
        reader = asyncio.StreamReader()
        protocol = asyncio.StreamReaderProtocol(reader)
        await asyncio.get_event_loop().connect_read_pipe(lambda: protocol, sys.stdin.buffer)
        writer_transport, writer_protocol = await asyncio.get_event_loop().connect_write_pipe(
            asyncio.streams.FlowControlMixin, sys.stdout.buffer
        )
        writer = asyncio.StreamWriter(writer_transport, writer_protocol, None, asyncio.get_event_loop())

        while True:
            try:
                header_line = await reader.readline()
                if not header_line:
                    break
                header = header_line.decode().strip()
                content_length = 0
                if header.startswith("Content-Length:"):
                    content_length = int(header.split(":")[1].strip())
                else:
                    continue
                await reader.readline()
                body = await reader.readexactly(content_length)
                request = json.loads(body.decode())
                response = await self._handle_request(request)
                if response:
                    response_body = json.dumps(response)
                    message = f"Content-Length: {len(response_body)}\r\n\r\n{response_body}"
                    writer.write(message.encode())
                    await writer.drain()
            except asyncio.IncompleteReadError:
                break
            except Exception as e:
                sys.stderr.write(f"MCP Export Server error: {e}\n")
                sys.stderr.flush()

    async def _handle_request(self, request: dict) -> dict | None:
        method = request.get("method", "")
        request_id = request.get("id")
        params = request.get("params", {})

        if method == "initialize":
            return {"jsonrpc": "2.0", "id": request_id, "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {"listChanged": False}},
                "serverInfo": self.server_info,
            }}
        elif method == "notifications/initialized":
            return None
        elif method == "tools/list":
            return {"jsonrpc": "2.0", "id": request_id, "result": {"tools": self.tools}}
        elif method == "tools/call":
            result = await self.handle_tool_call(params.get("name", ""), params.get("arguments", {}))
            return {"jsonrpc": "2.0", "id": request_id, "result": result}
        elif method == "ping":
            return {"jsonrpc": "2.0", "id": request_id, "result": {}}
        else:
            return {"jsonrpc": "2.0", "id": request_id, "error": {"code": -32601, "message": f"Method not found: {method}"}}


async def main():
    server = ExportMCPServer()
    await server.run_stdio()


if __name__ == "__main__":
    asyncio.run(main())
